/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package membership.system;

import java.util.ArrayList;

/**
 *
 * @author hortonr6
 */
public class NewMemberUI extends javax.swing.JFrame
{
    private NewMemberController newCon;
    private ArrayList<javax.swing.JTextField> textFields;
    private ArrayList<javax.swing.JComboBox> comboBoxes;
    /**
     * Creates new form NewMember
     */
    public NewMemberUI()
    {
        initComponents();
        warningLabel.setText("");
        newCon = new NewMemberController();
        
        textFields = new ArrayList<javax.swing.JTextField>();
        textFields.add(firstNameEntry);
        textFields.add(lastNameEntry);
        textFields.add(firstNameEntry);
        textFields.add(contactNumEntry);
        textFields.add(emailEntry);
        textFields.add(addressLine1Entry);
        textFields.add(addressLine2Entry);
        textFields.add(cityEntry);
        textFields.add(postCodeEntry);
        textFields.add(countyEntry);
        textFields.add(cardNumEntry);
        textFields.add(cardNameEntry);
        textFields.add(securityEntry);
        
        comboBoxes = new ArrayList<javax.swing.JComboBox>();
        comboBoxes.add(genderCombo);
        comboBoxes.add(dobDayCombo);
        comboBoxes.add(dobMonthCombo);
        comboBoxes.add(dobYearCombo);
        comboBoxes.add(membershipCombo);
        comboBoxes.add(expiryMonthCombo);
        comboBoxes.add(expiryYearCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        timeAndDateLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameEntry = new javax.swing.JTextField();
        lastNameEntry = new javax.swing.JTextField();
        contactNumLabel = new javax.swing.JLabel();
        contactNumEntry = new javax.swing.JTextField();
        addressLine1Label = new javax.swing.JLabel();
        addressLine1Entry = new javax.swing.JTextField();
        addressLine2Label = new javax.swing.JLabel();
        addressLine2Entry = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityEntry = new javax.swing.JTextField();
        countyLabel = new javax.swing.JLabel();
        countyEntry = new javax.swing.JTextField();
        postCodeLabel = new javax.swing.JLabel();
        postCodeEntry = new javax.swing.JTextField();
        membershipLabel = new javax.swing.JLabel();
        membershipCombo = new javax.swing.JComboBox<>();
        billingInfoLabel = new javax.swing.JLabel();
        cardNumLabel = new javax.swing.JLabel();
        cardNumEntry = new javax.swing.JTextField();
        cardNameLabel = new javax.swing.JLabel();
        cardNameEntry = new javax.swing.JTextField();
        expiryDateLabel = new javax.swing.JLabel();
        expiryMonthCombo = new javax.swing.JComboBox<>();
        expiryYearCombo = new javax.swing.JComboBox<>();
        customerDetailsLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailEntry = new javax.swing.JTextField();
        securityEntry = new javax.swing.JTextField();
        securityLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        dobMonthCombo = new javax.swing.JComboBox<>();
        dobYearCombo = new javax.swing.JComboBox<>();
        dobDayCombo = new javax.swing.JComboBox<>();
        genderLabel = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        timeAndDateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeAndDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeAndDateLabel.setText("Time and Date");

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        firstNameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameEntryActionPerformed(evt);
            }
        });

        contactNumLabel.setText("Contact Number");

        contactNumEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumEntryActionPerformed(evt);
            }
        });

        addressLine1Label.setText("Address Line 1");

        addressLine1Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine1EntryActionPerformed(evt);
            }
        });

        addressLine2Label.setText("Address Line 2");

        addressLine2Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine2EntryActionPerformed(evt);
            }
        });

        cityLabel.setText("City/Town");

        cityEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityEntryActionPerformed(evt);
            }
        });

        countyLabel.setText("County");

        countyEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countyEntryActionPerformed(evt);
            }
        });

        postCodeLabel.setText("Post Code");

        postCodeEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postCodeEntryActionPerformed(evt);
            }
        });

        membershipLabel.setText("Membership");

        membershipCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Membership", "Silver", "Platinum" }));
        membershipCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipComboActionPerformed(evt);
            }
        });

        billingInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        billingInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billingInfoLabel.setText("Billing Information");

        cardNumLabel.setText("Card Number");

        cardNumEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumEntryActionPerformed(evt);
            }
        });

        cardNameLabel.setText("Name on Card");

        cardNameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNameEntryActionPerformed(evt);
            }
        });

        expiryDateLabel.setText("Expiry Date");

        expiryMonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        expiryMonthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryMonthComboActionPerformed(evt);
            }
        });

        expiryYearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));
        expiryYearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryYearComboActionPerformed(evt);
            }
        });

        customerDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerDetailsLabel.setText("Customer Details");

        emailLabel.setText("Email Address");

        emailEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailEntryActionPerformed(evt);
            }
        });

        securityEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityEntryActionPerformed(evt);
            }
        });

        securityLabel.setText("Security");

        dateOfBirthLabel.setText("Date of Birth");

        dobMonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        dobMonthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobMonthComboActionPerformed(evt);
            }
        });

        dobYearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        dobYearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobYearComboActionPerformed(evt);
            }
        });

        dobDayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dobDayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobDayComboActionPerformed(evt);
            }
        });

        genderLabel.setText("Gender");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Other", "Prefer Not To Say" }));
        genderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(contactNumLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contactNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(customerDetailsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressLine1Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(postCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(postCodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cityEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(countyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(countyEntry))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addressLine1Entry))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addressLine2Label)
                        .addGap(10, 10, 10)
                        .addComponent(addressLine2Entry))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billingInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cardNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cardNumLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cardNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expiryDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(securityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(expiryMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(expiryYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(securityEntry)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(membershipLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(membershipCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(genderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dateOfBirthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dobDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(dobMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dobYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(customerDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumLabel)
                    .addComponent(contactNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfBirthLabel)
                    .addComponent(dobMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLine1Label)
                    .addComponent(addressLine1Entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLine2Label)
                    .addComponent(addressLine2Entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countyLabel)
                    .addComponent(countyEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postCodeLabel)
                    .addComponent(postCodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membershipLabel)
                    .addComponent(membershipCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(billingInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumLabel)
                    .addComponent(securityEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNameLabel)
                    .addComponent(expiryDateLabel)
                    .addComponent(expiryMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        warningLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(165, 165, 165)
                        .addComponent(warningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeAndDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton)
                        .addComponent(timeAndDateLabel))
                    .addComponent(warningLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        backToMainMenu();
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        submitNewMember();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelNewMember();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void firstNameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameEntryActionPerformed

    private void contactNumEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumEntryActionPerformed

    private void addressLine1EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine1EntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine1EntryActionPerformed

    private void addressLine2EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine2EntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine2EntryActionPerformed

    private void cityEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityEntryActionPerformed

    private void countyEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countyEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countyEntryActionPerformed

    private void postCodeEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postCodeEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postCodeEntryActionPerformed

    private void membershipComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membershipComboActionPerformed

    private void cardNumEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumEntryActionPerformed

    private void cardNameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNameEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNameEntryActionPerformed

    private void expiryMonthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryMonthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryMonthComboActionPerformed

    private void expiryYearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryYearComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryYearComboActionPerformed

    private void emailEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEntryActionPerformed

    private void securityEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityEntryActionPerformed

    private void dobMonthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobMonthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobMonthComboActionPerformed

    private void dobYearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobYearComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobYearComboActionPerformed

    private void dobDayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobDayComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobDayComboActionPerformed

    private void genderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMemberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMemberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMemberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMemberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMemberUI().setVisible(true);
            }
        });
    }
    
    private void backToMainMenu()
    {
	dispose();
    }

    private void submitNewMember()
    {
        boolean allText = false;
        boolean allCombo = false;
        
        for(javax.swing.JTextField field : textFields)
        {
            if(field.getText() == "")
            {
                allText = false;
                break;
            }
            else
            {
                allText = true;
            }
        }
        
        for(javax.swing.JComboBox combo : comboBoxes)
        {
            if(combo.getSelectedIndex() == 0)
            {
                allCombo = false;
                break;
            }
            else
            {
                allCombo = true;
            }
        }
        
        if(allText && allCombo)
        {
            AdvisorUI.currentMember = new Member();
            submitPersonalDetails();
            submitAddressDetails();
            submitBillingDetails();
            
            switch(newCon.completeNewMember())
            {
                case 0:
                    warningLabel.setText("Registration Complete");
                    break;
                case 1:
                    warningLabel.setText("Connection Error");
                    break;
                case 2:
                    warningLabel.setText("SQL Error");
                    break;
                default:
                    warningLabel.setText("Error");
            }
        }
    }
    
    private void submitPersonalDetails()
    {
        // Get personal details from the form
        String firstName = firstNameEntry.getText();
        String lastName = lastNameEntry.getText();
        String email = emailEntry.getText();
        String dateOfBirth = dobDayCombo.getSelectedItem().toString() + "/" +
                dobMonthCombo.getSelectedItem().toString() + "/" +
                dobYearCombo.getSelectedItem().toString();
        int contactNum = Integer.parseInt(contactNumEntry.getText());
        
        int membershipType = 0;
        switch(membershipCombo.getSelectedItem().toString())
        {
            case "Silver":
                membershipType = 1;
                break;
            case "Platinum":
                membershipType = 3;
                break;
            default:
                membershipType = 1;
        }
        
        int gender = 0;
        switch(genderCombo.getSelectedItem().toString())
        {
            case "Male":
                gender = 1;
                break;
            case "Female":
                gender = 2;
                break;
            case "Other":
                gender = 3;
                break;
            case "Prefer Not To Say":
                gender = 4;
                break;
            default:
                gender = 4;
        }
        
        // Submit details to controller
        newCon.addPersonalDetails(firstName, lastName, email, contactNum,
                membershipType, dateOfBirth, gender);
    }
    
    private void submitAddressDetails()
    {
        // Get address details from the form
        String addressLine1 = addressLine1Entry.getText();
        String addressLine2 = addressLine2Entry.getText();
        String city = cityEntry.getText();
        String postCode = postCodeEntry.getText();
        String county = countyEntry.getText();
        
        // Submit details to controller
        newCon.addAddressDetails(addressLine1, addressLine2, city, county, postCode);
    }
    
    private void submitBillingDetails()
    {
        int cardNum = Integer.parseInt(cardNumEntry.getText());
        String cardName = cardNameEntry.getText();
        int security = Integer.parseInt(securityEntry.getText());
        int expMonth = Integer.parseInt(expiryMonthCombo.getSelectedItem().toString());
        int expYear = Integer.parseInt(expiryYearCombo.getSelectedItem().toString());
        
        newCon.addBillingDetails(cardNum, cardName, expMonth, expYear, security);
    }

    private void cancelNewMember()
    {
        // Clear form data
	dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressLine1Entry;
    private javax.swing.JLabel addressLine1Label;
    private javax.swing.JTextField addressLine2Entry;
    private javax.swing.JLabel addressLine2Label;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel billingInfoLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cardNameEntry;
    private javax.swing.JLabel cardNameLabel;
    private javax.swing.JTextField cardNumEntry;
    private javax.swing.JLabel cardNumLabel;
    private javax.swing.JTextField cityEntry;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField contactNumEntry;
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JTextField countyEntry;
    private javax.swing.JLabel countyLabel;
    private javax.swing.JLabel customerDetailsLabel;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JComboBox<String> dobDayCombo;
    private javax.swing.JComboBox<String> dobMonthCombo;
    private javax.swing.JComboBox<String> dobYearCombo;
    private javax.swing.JTextField emailEntry;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel expiryDateLabel;
    private javax.swing.JComboBox<String> expiryMonthCombo;
    private javax.swing.JComboBox<String> expiryYearCombo;
    private javax.swing.JTextField firstNameEntry;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameEntry;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JComboBox<String> membershipCombo;
    private javax.swing.JLabel membershipLabel;
    private javax.swing.JTextField postCodeEntry;
    private javax.swing.JLabel postCodeLabel;
    private javax.swing.JTextField securityEntry;
    private javax.swing.JLabel securityLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel timeAndDateLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
